package consistenthashing

import "github.com/OriD-19/distributed_cache/lruCache"

type CacheNode struct {
	ID          string
	Status      CacheNodeStatus
	CacheClient *lruCache.LRUCache
	Addr        string // IP address to contact the node via TC
}

func NewCacheNode(cache *lruCache.LRUCache, id, addr string) *CacheNode {

	var cacheNode CacheNode

	cacheNode.Status = RUNNING // running node by default
	cacheNode.CacheClient = cache
	cacheNode.ID = id

	// of course, in a real environment, this thing spins up in its own dedicated
	// [virtual] machine, and gets assigned an IP address (for exapmle, in the cloud)
	cacheNode.Addr = addr // IP address randomly generated by our server

	return &cacheNode
}
